[tool.poetry]
name = "backpy"
version = "0.1.0"
description = ""
authors = ["Isaac Ferreira Filho"]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^5.4.1"
flake8 = "^3.7.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
